### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by Nini133** [cepruo/plsql-color-schemes#5]
Hey ! How can I remove themes I installed ? PLSQL 12

**Comment by cepruo** [comment]
There is no list of themes stored in 12 version. So there will be only one active existing settings set. You can substitute it by default.ini (load it the same way as any other theme described). File presented in repo for the reference. Or if you have system preferences set untouched, you can remove your custom set and create new one. It will be created from scratch, with the default settings set.
